title: Bogdan Banasiak
logo: assets/img/main_photo.png
description: If you are interested, you can also visit my <a href="https://www.kaggle.com/banasb">Kaggle</a> profile, where you can find many interesting analysis and projects.
show_downloads: false
theme: jekyll-theme-minimal
