title: Bogdan Banasiak
logo: assets/img/main_photo.png
description: "If you are interested, you can also visit my [GtitHub](https://github.com/BanasiakB) and [Kaggle](https://www.kaggle.com/bogdanb0), to see more interesting projects."
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
