title: Bogdan Banasiak
logo: assets/img/main_photo.png
description: If you are interested, you can also visit my <a href="https://github.com/BanasiakB">GtitHub</a> and <a href="https://www.kaggle.com/bogdanb0">Kaggle</a>, to see more interesting projects.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
